### PR TITLE
Improve heap layout, and some refactoring.

### PR DESCRIPTION
**Pull request by dimonomid**
For details on these issues, with visual heap maps and detailed explanation, see the article: [Embedded Heap Behaviour: Analysis and Improvement](https://blog.cesanta.com/embedded-heap-behaviour-analysis-and-improvement).

Configuration is changed as well: now, each particular application should provide application-dependent `umm_malloc_cfg.h`; therefore, library code is the same for any client application. As an example, see `umm_malloc_cfg_example.h`.

At least, it should provide `UMM_MALLOC_CFG__HEAP_ADDR`, `UMM_MALLOC_CFG__HEAP_SIZE`.

Optionally, added integrity check and poisoning (disabled by default).

### CODE REVIEW

**Comment by rhempel** [comment]
Thks @dimonomid for your extra work to polish up this library!

**Comment by dimonomid** [comment]
It's a pleasure, and thanks for the review!

**Comment by andig** [comment]
@dimonomid what is `UMM_POISONED_BLOCK_LEN_TYPE` really used for? I can see where its stored but not for what purpose?

**Comment by dimonomid** [comment]
@andig it is needed to store exact requested size of the block. Without it, umm_malloc doesn't care of the granularity less than 8 bytes (size of the block). So, for example, there's no difference if user requested 2 or 4 bytes: it will allocate 1 block. So, without storing exact size, and by allocating some non-aligned size, we would have been unable to catch overflows by just a few bytes.

**Comment by andig** [comment]
Understood- but where is that actually used? From what I've seen poison is always applied with fixed size, so how would those overflows be detected? Must admit I've spent some time looking at https://github.com/cesanta/umm_malloc as this repo didn't have poison yet.

**Comment by dimonomid** [comment]
See function `check_poison_block()`:
```
/* ... */
    pc_cur = pc + *((UMM_POISONED_BLOCK_LEN_TYPE *)pc) - UMM_POISON_SIZE_AFTER;
    if (!check_poison(pc_cur, UMM_POISON_SIZE_AFTER, "after")) {
      UMM_HEAP_CORRUPTION_CB();
      ok = 0;
      goto clean;
    }
/* ... */
```
The `*((UMM_POISONED_BLOCK_LEN_TYPE *)pc)` part is exactly where it is used. We interpret a pointer to buffer as a pointer to `UMM_POISONED_BLOCK_LEN_TYPE`, and add this number to the pointer to buffer, therefore we get a pointer to the ending poison.

**Comment by dimonomid** [comment]
You may want to try to actually overflow some buffer by 1 byte, and make sure your `UMM_HEAP_CORRUPTION_CB()` callback is called.

**Comment by dimonomid** [comment]
By the way, note that the current poison implementation will only work on little-endian architectures. I had plans to improve it, but eventually I forgot :( hopefully will do that in a near future, seems trivial.

**Comment by andig** [comment]
Ahhh, I see, thank you! Didn't notice the cast.

**Pull request merged**
